site_name: ThothAI Backend Documentation
site_url: https://sitename.example
theme:
  name: material
  favicon: assets/favicon.ico
  icon:
    logo: simple/surveymonkey
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Install:
      - Getting Sources: 1-install/1.1-sources_cloning.md
      - Docker Installation: 1-install/1.2-docker.md
      - Local Installation: 1-install/1.3-local.md
      - Quick Setup: 1-install/1.4-quick_setup.md
  - Quick Start:
      - Frontend Quick Start: 2-quickstart/2.1-quickstart_frontend.md
  - Reference Manual:
      - Setup:
        - Setup Process: 3-user_manual/3.1-setup/3.1.0-setup_process.md
        - Common Setup Features: 3-user_manual/3.1-setup/3.1.01-common_setup.md
        - Authentication:
          - Groups: 3-user_manual/3.1-setup/3.1.1-authentication/3.1.1.1-groups.md
          - Users: 3-user_manual/3.1-setup/3.1.1-authentication/3.1.1.2-users.md
          - Group profiles: 3-user_manual/3.1-setup/3.1.1-authentication/3.1.1.3-group_profiles.md
        - AI Models and Agents:
          - Basic AI Models: 3-user_manual/3.1-setup/3.1.2-AI_models_and_agents/3.1.2.1-basic_ai_models.md
          - AI Models: 3-user_manual/3.1-setup/3.1.2-AI_models_and_agents/3.1.2.2-ai_models.md
          - Agents: 3-user_manual/3.1-setup/3.1.2-AI_models_and_agents/3.1.2.3-agents.md
        - Vector DBs: 3-user_manual/3.1-setup/3.1.3-vector_database/3.1.3.1-vector_db.md
        - SQL Database: 
          - Sql dbs: 3-user_manual/3.1-setup/3.1.4-SQL_database/3.1.4.1-sql_dbs.md
          - Sql tables: 3-user_manual/3.1-setup/3.1.4-SQL_database/3.1.4.2-sql_tables.md
          - Sql columns: 3-user_manual/3.1-setup/3.1.4-SQL_database/3.1.4.3-sql_columns.md
          - Relationships: 3-user_manual/3.1-setup/3.1.4-SQL_database/3.1.4.4-relationships.md
        - Settings:  3-user_manual/3.1-setup/3.1.5.1-settings.md
        - Workspaces: 3-user_manual/3.1-setup/3.1.6.1-workspaces.md
      - Preprocessing:
          - Why Preprocessing?: 3-user_manual/3.2-preprocessing/3.2.1-why_the_preprocessing.md
          - Hints: 3-user_manual/3.2-preprocessing/3.2.2-hints.md
          - Questions: 3-user_manual/3.2-preprocessing/3.2.3-questions.md
          - Update Columns Description: 3-user_manual/3.2-preprocessing/3.2.4-update_columns_description.md
          - Run Preprocessing: 3-user_manual/3.2-preprocessing/3.2.5-run_preprocessing.md
      - Workflow:
        - Preliminary Steps: 4-reference_manual/4.3-workflow/4.3.1-preliminary_steps.md
        - Main Workflow: 4-reference_manual/4.3-workflow/4.3.2-main_workflow.md
        - Basic Generation Workflow: 4-reference_manual/4.3-workflow/4.3.3-basic_generation_workflow.md
        - Titanic Generation Workflow: 4-reference_manual/4.3-workflow/4.3.4-titanic_generation_workflow.md
        - Final Steps: 4-reference_manual/4.3-workflow/4.3.5-final_steps.md

      - Logging:
        - Logfire: 3-user_manual/3.4-logging/3.4.1-logfire.md
        - Log Management: 3-user_manual/3.4-logging/3.4.2-log_management.md
      - Comments: 4-reference_manual/4.2-comments.md
      - Hints: 4-reference_manual/4.4-hints.md
      - Questions: 4-reference_manual/4.5-questions.md
      - Roadmap: 3-user_manual/3.8-roadmap.md
  - References: references.md
  - LSH preprocessing: 4-reference_manual/4.7-lsh_preprocessing.md
  - Text-to-SQL: text-to-SQL.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@tylconsulting
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcopancotti
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/custom.js

copyright: Copyright &copy; 2025 Marco Pancotti


