site_name: ThothAI Backend Documentation
site_url: https://sitename.example
dev_addr: 127.0.0.1:8199
theme:
  name: material
  favicon: assets/favicon.ico
  icon:
    logo: simple/surveymonkey
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Docker Install:
      - Sources Cloning: 1-docker_install/1.1-sources_cloning.md
      - Docker Assisted: 1-docker_install/1.2-docker_assisted.md
  - Local Install:
      - Sources Cloning: 2-local_install/2.1-sources_cloning.md
      - Local: 2-local_install/2.2-local.md
  - Quick Start:
      - Quick Setup: 3-quickstart/3.1-quick_setup.md
      - Quick Start Frontend: 3-quickstart/3.2-quickstart_frontend.md
  - User Manual:
      - Setup:
          - Setup Process:
            - Setup Process: 4-user_manual/4.1-setup/4.1.1-setup_process/4.1.1.1-setup_process.md
          - Common Setup:
             - Common Setup: 4-user_manual/4.1-setup/4.1.2-common_setup/4.1.2.1-common_setup.md
          - AI Models And Agents:
             - Basic AI Models: 4-user_manual/4.1-setup/4.1.3-AI_models_and_agents/4.1.3.1-basic_ai_models.md
             - AI Models: 4-user_manual/4.1-setup/4.1.3-AI_models_and_agents/4.1.3.2-ai_models.md
             - Agents: 4-user_manual/4.1-setup/4.1.3-AI_models_and_agents/4.1.3.3-agents.md
          - Authentication:
             - Groups: 4-user_manual/4.1-setup/4.1.4-authentication/4.1.4.1-groups.md
             - Users: 4-user_manual/4.1-setup/4.1.4-authentication/4.1.4.2-users.md
             - Group Profiles: 4-user_manual/4.1-setup/4.1.4-authentication/4.1.4.3-group_profiles.md
          - Vector Database:
              - Vector DB: 4-user_manual/4.1-setup/4.1.5-vector_database/4.1.5.1-vector_db.md
          - SQL Database:
              - SQL DBs: 4-user_manual/4.1-setup/4.1.6-SQL_database/4.1.6.1-sql_dbs.md
              - SQL Tables: 4-user_manual/4.1-setup/4.1.6-SQL_database/4.1.6.2-sql_tables.md
              - SQL Columns: 4-user_manual/4.1-setup/4.1.6-SQL_database/4.1.6.3-sql_columns.md
              - Relationships: 4-user_manual/4.1-setup/4.1.6-SQL_database/4.1.6.4-relationships.md
          - Workspaces:
              - Workspaces: 4-user_manual/4.1-setup/4.1.7-workspaces/4.1.7.1-workspaces.md
          - Settings:
              - Settings: 4-user_manual/4.1-setup/4.1.8-settings/4.1.8.1-settings.md
      - Preprocessing:
          - Why The Preprocessing: 4-user_manual/4.2-preprocessing/4.2.1-why_the_preprocessing.md
          - Hints: 4-user_manual/4.2-preprocessing/4.2.2-hints.md
          - Questions: 4-user_manual/4.2-preprocessing/4.2.3-questions.md
          - Update Columns Description: 4-user_manual/4.2-preprocessing/4.2.4-update_columns_description.md
          - Run Preprocessing: 4-user_manual/4.2-preprocessing/4.2.5-run_preprocessing.md
      - Logging:
          - Logfire: 4-user_manual/4.3-logging/4.3.1-logfire.md
          - Log Management: 4-user_manual/4.3-logging/4.3.2-log_management.md
      - Frontend:
          - Frontend: 4-user_manual/4.5-frontend/4.5.1-frontend.md
      - Roadmap:
          - Roadmap: 4-user_manual/4.8-roadmap/4.8.1-roadmap.md
  - Reference Manual:
      - Reference Manual:
          - Reference Manual Map: 5-reference_manual/5.1-reference_manual/5.1.1-reference_manual_map.md
      - Comments:
          - Comments: 5-reference_manual/5.2-comments/5.2.1-comments.md
      - Workflow:
          - Preliminary Steps: 5-reference_manual/5.3-workflow/5.3.1-preliminary_steps.md
          - Main Workflow: 5-reference_manual/5.3-workflow/5.3.2-main_workflow.md
          - Basic Generation Workflow: 5-reference_manual/5.3-workflow/5.3.3-basic_generation_workflow.md
          - Titanic Generation Workflow: 5-reference_manual/5.3-workflow/5.3.4-titanic_generation_workflow.md
          - Final Steps: 5-reference_manual/5.3-workflow/5.3.5-final_steps.md
      - Hints:
          - Hints: 5-reference_manual/5.4-hints/5.4-hints.md
      - Questions:
          - Questions: 5-reference_manual/5.5-questions/5.5-questions.md
      - Columns:
          - Columns: 5-reference_manual/5.6-columns/5.6-columns.md
      - LSH Processing:
          - LSH Preprocessing: 5-reference_manual/5.7-lsh_processing/5.7-lsh_preprocessing.md
  - References: references.md
  - Text to SQL: text-to-SQL.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@tylconsulting
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcopancotti
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/custom.js

copyright: Copyright &copy; 2025 Marco Pancotti


