site_name: Thoth AI Backend Documentation
site_url: https://sitename.example
theme:
  name: material
  favicon: assets/favicon.ico
  icon:
    logo: simple/surveymonkey
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Installazione: 
    - Acquisizione sorgenti: install/sources_cloning.md
    - Installazione su Docker: install/docker.md
    - Installazione in locale: install/local.md
  - Setup:
    -  Il processo di setup: setup/setup_process.md
    - L'Authentication:
      - Groups: setup/authentication/groups.md
      - Group profiles: setup/authentication/group_profiles.md
      - Users: setup/authentication/users.md
    - Gli AI Models e gli Agenti:
      - Basic ai models: setup/AI_models_and_agents/basic_ai_models
      - Ai Models: setup/AI_models_and_agents/ai_models.md
      - Agents: setup/AI_model_and_agents//agents.md
    - I Database relazionali:
      - Sql dbs: setup/Sql_database/sql_dbs.md
      - Sql tables: setup/Sql_database/sql_tables.md
      - Sql columns: setup/Sql_database//sql_columns.md
      - Relationships: setup/Sql_database/relationships.md
  - Il preprocessing: 
    - Hints: preprocessing/hints.md
    - Questions: preprocessing/questions.md
    - Update Columns Description: preprocessing/update_columns_description.md
    - Run Preprocessing: preprocessing/run_preprocessing.md
  - Il logging:
    - Logfire: logging/logfire.md
    - Log management: logging/log_management.md
  - I commenti : comments.md
  - Gli hints: hints.md
  - Le questions: questions.md
  - La Roadmap di Thoth: roadmap.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@tylconsulting
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcopancotti

copyright: Copyright &copy; 2025 Marco Pancotti
