site_name: Thoth AI Backend Documentation
site_url: https://sitename.example
theme:
  name: material
  favicon: assets/favicon.ico
  icon:
    logo: simple/surveymonkey
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Installazione: 
    - Acquisizione sorgenti: install/sources_cloning.md
    - Installazione su Docker: install/docker.md
    - Installazione in locale: install/local.md
  - Setup:
    - Authentication:
      - Groups: setup/authentication/groups.md
      - Groups Permissions: setup/authentication/groups_permissions.md
      - Users: setup/authentication/users.md
    - AI Models and Agents:
      - AI Models: setup/ai_models.md
      - Agents: setup/agents.md
  - Django Backend: django_backend.md
  - Il preprocessing: 
    - Hints: preprocessing/hints.md
    - Questions: preprocessing/questions.md
    - Update Columns Description: preprocessing/update_columns_description.md
    - Run Preprocessing: preprocessing/run_preprocessing.md
  - Logfire e i llog di Thoth: logfire.md
  - La Roadmap: roadmap.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@tylconsulting
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcopancotti

copyright: Copyright &copy; 2025 Marco Pancotti
